
# ~BrieFlow analysis configuration file~

# All paths are resolved relative to the directory the workflow is run from.

# Parameters:
all:
  root_fp: brieflow_output/
preprocess:
  sbs_samples_fp: config/sbs_samples.tsv
  sbs_combo_fp: config/sbs_combo.tsv
  phenotype_samples_fp: config/phenotype_samples.tsv
  phenotype_combo_fp: config/phenotype_combo.tsv
  sbs_data_format: tiff
  sbs_data_organization: tile
  sbs_channel_order:
  - 405_nm_Ex
  - 561_nm_Ex_-_1
  - 561_nm_Ex_-_2
  - 638_nm_Ex_-_1
  - 638_nm_Ex_-_2
  sbs_channel_order_flip: false
  sbs_metadata_samples_df_fp: config/sbs_metadata_samples.tsv
  phenotype_data_format: nd2
  phenotype_data_organization: tile
  phenotype_channel_order: null
  phenotype_channel_order_flip: false
  phenotype_round_order:
  - 1
  phenotype_metadata_samples_df_fp: null
  sample_fraction: 0.5
sbs:
  alignment_method: null
  channel_names:
  - DAPI
  - G
  - T
  - A
  - C
  upsample_factor: 2
  skip_cycles_indices: null
  manual_background_cycle_index: null
  extra_channel_indices:
  - 0
  max_filter_width: 2
  spot_detection_method: standard
  dapi_cycle: 1
  cyto_cycle: 1
  cyto_cycle_index: 0
  dapi_index: 0
  cyto_index: 1
  segmentation_method: cellpose
  gpu: false
  segment_cells: false
  df_barcode_library_fp: config/barcode_library.tsv
  sequencing_order: recomb_map
  threshold_peaks: 125
  call_reads_method: percentile
  bases:
  - G
  - T
  - A
  - C
  q_min: 0
  recomb_start: 1
  recomb_end: 0
  map_start: 1
  map_end: 12
  map_col: prefix_map
  recomb_col: prefix_recomb
  recomb_filter_col: Q_recomb
  error_correct: true
  recomb_q_thresh: 0
  barcode_info_cols:
  - gene_symbol
  max_distance: 2
  sort_calls: peak
  mode: null
  peak_width: 5
  nuclei_diameter: 7
  cell_diameter: 10
  nuclei_flow_threshold: 0.3
  nuclei_cellprob_threshold: 1
  cell_flow_threshold: 1
  cell_cellprob_threshold: 0
  cyto_model: cyto3
phenotype:
  foci_channel: null
  channel_names:
  - DAPI
  align: null
  dapi_index: 0
  cyto_index: 0
  segmentation_method: cellpose
  reconcile: contained_in_cells
  gpu: false
  cp_method: cp_multichannel
  mode: null
  nuclei_diameter: 20.02674353437364
  cell_diameter: 38.014824519842385
  nuclei_flow_threshold: 0.4
  nuclei_cellprob_threshold: 0.0
  cell_flow_threshold: 1
  cell_cellprob_threshold: 0
  cyto_model: cyto3
merge:
  merge_combo_fp: config/merge_combo.tsv
  sbs_metadata_cycle: 1
  sbs_metadata_channel: null
  ph_metadata_channel: null
  alignment_flip_x: true
  alignment_flip_y: false
  alignment_rotate_90: false
  alignment_reference_df: 2
  initial_sites:
  - - 1
    - 0
  - - 231
    - 11
  - - 560
    - 25
  - - 943
    - 49
  - - 1123
    - 53
  - - 1357
    - 67
  det_range:
  - 0.09
  - 0.12
  score: 0.1
  threshold: 10
